name: Build

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Install Ginkgo
        run: |
          go install github.com/onsi/ginkgo/v2/ginkgo
          
      - name: Test
        run: |
          ginkgo -failOnPending -randomizeAllSpecs -race -trace -r 

