name: Build

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: get go version
        run: echo "GO_VERSION=$(cat go.mod |grep "^go "| cut -f 2 -d " ")" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install Ginkgo
        run: |
          go install github.com/onsi/ginkgo/v2/ginkgo
          
      - name: Test
        run: |
          ginkgo  --fail-on-pending --randomize-all --race --cover --trace -r

