name: Build

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: get lint version
        run: echo "LINT_VERSION=$(cat .tool-versions| grep golangci-lint | sed -r 's/^golangci-lint ([0-9]+\.[0-9]+).*/\1/')" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v${{env.LINT_VERSION}}